application: partymixer3
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /html
  static_dir: html

- url: /.*
  script: main.py


